name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Check package can be imported
        run: |
          node -e "
            console.log('Testing package import...');
            const pkg = require('./lib/index.js');
            console.log('Available exports:', Object.keys(pkg));
            if (!pkg.BaseCrudApi) throw new Error('BaseCrudApi not exported');
            console.log('✅ Package import successful');
          "

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript compilation
        run: npm run build

      - name: Verify package structure
        run: |
          echo "Checking lib directory structure..."
          ls -la lib/
          
          echo "Checking for required files..."
          test -f lib/index.js || (echo "❌ lib/index.js missing" && exit 1)
          test -f lib/index.d.ts || (echo "❌ lib/index.d.ts missing" && exit 1)
          test -f lib/base-crud.js || (echo "❌ lib/base-crud.js missing" && exit 1)
          test -f lib/base-crud.d.ts || (echo "❌ lib/base-crud.d.ts missing" && exit 1)
          
          echo "✅ Package structure verified"

  validate-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Validate package.json
        run: |
          echo "Validating package.json structure..."
          
          # Check required fields
          node -e "
            const pkg = require('./package.json');
            const required = ['name', 'version', 'description', 'main', 'types', 'author', 'license', 'repository'];
            for (const field of required) {
              if (!pkg[field]) throw new Error(\`Missing required field: \${field}\`);
            }
            console.log('✅ Package.json validation passed');
          "

      - name: Check npm package contents
        run: |
          echo "Checking what would be published to npm..."
          npm pack --dry-run
