# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: http://registry.npmjs.org/
      - run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - run: npm rebuild && npm run prepare --if-present

  publish-npm:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: http://registry.npmjs.org/
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - run: npm run build
      - run: git config --global user.email autobot@aftersignals.com
      - run: git config --global user.name "AfterSignals Automation"
      - run: npm version patch -m "[skip ci] publish new version"
      - run: git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
